### ISSUE TITLE
[BUG] Trailing commas in meta keywords when no tags or no keywords in metadata

### ISSUE THREAD

**Issue by vokimon** [Pelican-Elegant/elegant#618]
## Mandatory Step

- [x] I am using latest production release of Elegant

## Recommended Step

- [ ] I have attached link to my blog source code repository, so that developers can try to reproduce the issue at the end
- [ ] I can't my source code but I have linked my pelican configuration files to help developers reproduce the issue

## Description

Trailing commas appear in the content of the meta-keywords tag, whenever no tags or no keywords are set.

If you define no keyword then a trailing comma will appear at the end.

    <meta name="keywords" content="mytag1, mytag2, mycategory, " />

Likewise when metadata has no keywords, a trailing comma appear at the end of the 

    <meta name="keywords" content=", mycategory, kwd1, kwd2" />

When both, keywords and tags, are missing:

    <meta name="keywords" content=", mycategory, " />

To reproduce it create a page with category but no tags or no keywords and generate the website. Then look at the generated meta-keyword tag.

It should create a list with all keyword like objects (tags, categories, keywords) and then join then with `', '`. If not an empty element '' is joined instead of tags or keywords.

    <meta name="keywords" content="mycategory" />
